// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/login/avatar.vue')['default']
    Common: typeof import('./src/components/common.vue')['default']
    Custom: typeof import('./src/components/custom.vue')['default']
    Editor: typeof import('./src/components/editor.vue')['default']
    Login: typeof import('./src/components/login/login.vue')['default']
    Rules: typeof import('./src/components/rules.vue')['default']
    Settings: typeof import('./src/components/settings.vue')['default']
    Sidebar: typeof import('./src/components/sidebar.vue')['default']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCell: typeof import('@varlet/ui')['_CellComponent']
    VarCol: typeof import('@varlet/ui')['_ColComponent']
    VarDialog: typeof import('@varlet/ui')['_DialogComponent']
    VarForm: typeof import('@varlet/ui')['_FormComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarOption: typeof import('@varlet/ui')['_OptionComponent']
    VarRow: typeof import('@varlet/ui')['_RowComponent']
    VarSelect: typeof import('@varlet/ui')['_SelectComponent']
    VarTab: typeof import('@varlet/ui')['_TabComponent']
    VarTabItem: typeof import('@varlet/ui')['_TabItemComponent']
    VarTabs: typeof import('@varlet/ui')['_TabsComponent']
    VarTabsItems: typeof import('@varlet/ui')['_TabsItemsComponent']
  }
}

export { }
