// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Actions: typeof import('./src/components/Actions.vue')['default']
    Avatar: typeof import('./src/components/login/avatar.vue')['default']
    Common: typeof import('./src/components/common.vue')['default']
    CommonRule: typeof import('./src/components/CommonRule.vue')['default']
    Custom: typeof import('./src/components/custom.vue')['default']
    CustomRule: typeof import('./src/components/CustomRule.vue')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    HelpTips: typeof import('./src/components/HelpTips.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Ripple: typeof import('@varlet/ui')['_RippleComponent']
    Rule: typeof import('./src/components/Rule.vue')['default']
    Rules: typeof import('./src/components/Rules.vue')['default']
    Setting: typeof import('./src/components/Setting.vue')['default']
    Settings: typeof import('./src/components/Settings.vue')['default']
    SettingsCopy: typeof import('./src/components/Settings-copy.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCard: typeof import('@varlet/ui')['_CardComponent']
    VarCell: typeof import('@varlet/ui')['_CellComponent']
    VarCol: typeof import('@varlet/ui')['_ColComponent']
    VarDialog: typeof import('@varlet/ui')['_DialogComponent']
    VarForm: typeof import('@varlet/ui')['_FormComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarLoading: typeof import('@varlet/ui')['_LoadingComponent']
    VarMenu: typeof import('@varlet/ui')['_MenuComponent']
    VarOption: typeof import('@varlet/ui')['_OptionComponent']
    VarRow: typeof import('@varlet/ui')['_RowComponent']
    VarSelect: typeof import('@varlet/ui')['_SelectComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
    VarSwitch: typeof import('@varlet/ui')['_SwitchComponent']
    VarTab: typeof import('@varlet/ui')['_TabComponent']
    VarTabItem: typeof import('@varlet/ui')['_TabItemComponent']
    VarTabs: typeof import('@varlet/ui')['_TabsComponent']
    VarTabsItems: typeof import('@varlet/ui')['_TabsItemsComponent']
  }
}

export { }
