<script setup lang="ts">
import { ref, reactive, watch, computed, nextTick } from 'vue';
import { useHostsStore } from '@/stores/hosts';
import { useRulesStore } from '@/stores/rules';
import type { RuleResult, RuleType } from '@/stores/rules';
import { fetchIPs, pickBestIP } from '@/common/chinaz/parse';
import { Snackbar } from '@varlet/ui';
import '@varlet/ui/es/snackbar/style/index';

const props = defineProps(['show']);
const emit = defineEmits(['update:show']);

const activeTab = ref<RuleType>('regular');

const TYPE = {
  REGULAR: 'regular',
  REMOTE: 'remote',
  PREFER: 'prefer'
};

const tabs = reactive([
  {
    icon: 'file-document-outline',
    type: TYPE.REGULAR,
    name: '本地',
    disabled: false
  },
  { icon: 'weather-cloudy', type: TYPE.REMOTE, name: '远程', disabled: false },
  { icon: 'arrow-down', type: TYPE.PREFER, name: '优选', disabled: false }
]);

const rulesStore = useRulesStore();
const hostsStore = useHostsStore();
const hasError = ref(false);
const logContentEl = ref<HTMLElement>();

let data: RuleResult = {
  name: '',
  type: activeTab.value,
  urls: '',
  updateSchedule: 0,
  log: '',
  content: '',
  // 正在执行优选！！！
  running: false
};

// 规则数据
const rule = reactive(data);
const resetRule = () => {
  activeTab.value = 'regular';
  rule.name = '';
  rule.urls = '';
  rule.updateSchedule = 0;
  rule.log = '';
  rule.content = '';
  rule.running = false;
};

watch(
  () => props.show,
  (show) => {
    !show && resetRule();
  }
);

watch(
  () => rule.running,
  (running) => {
    if (running) {
      tabs.forEach(
        (tab) => tab.type !== activeTab.value && (tab.disabled = true)
      );
    } else {
      tabs.forEach((tab) => (tab.disabled = false));
    }
  }
);

// 关闭前，判断
const onBeforeClose = (
  action: 'confirm' | 'cancel' | 'close',
  done: Function
) => {
  if (rule.running) {
    return;
  }

  if (action === 'close' || action === 'cancel') {
    emit('update:show', false);
  } else {
    if (!hasError.value) {
      done();
      emit('update:show', false);
    } else {
      !rule.name && Snackbar['warning']('必须添加规则名！');
      rule.type === TYPE.REMOTE &&
        !rule.urls &&
        Snackbar['warning']('必须添加规则名或urls！');
      rule.type === TYPE.PREFER &&
        !rule.content &&
        Snackbar['warning']('未能优选检测！请稍后再试～');
    }
  }
};

// 打开添加的规则
const setActive = (id: string) => {
  hostsStore.currentId = id;
};

// 确定添加规则
function addRule() {
  rule.type = activeTab.value;
  switch (activeTab.value) {
    case TYPE.REGULAR:
      if (!rule.name) hasError.value = true;
      else {
        hasError.value = false;
        rulesStore.addRule(rule);
        setActive(rule.name);
      }
      break;
    case TYPE.REMOTE:
      {
        if (!rule.name || !rule.urls) hasError.value = true;
        else {
          hasError.value = false;
          rule.running = true;
          fetch(rule.urls).then(async (res) => {
            const hosts = await res.text();
            rule.content = hosts;
            rule.running = false;
            console.log('rule', rule);
            rulesStore.addRule(rule);
            emit('update:show', false);
            setActive(rule.name);
          });
        }
      }
      break;
    case TYPE.PREFER:
      hasError.value = false;
      rule.content += `\n# Generated by utools-plugin-hosts\n# https://github.com/chandlerver5/utools-plugin-hosts\n`;
      rulesStore.addRule(rule);
      emit('update:show', false);
      setActive(rule.name);
      break;
    default:
      break;
  }
}

// ----开始测试优选----
async function startPick() {
  console.log('asd');
  // 已有结果，接下来写入优选结果
  if (rule.log && !rule.running) {
    addRule();
    return;
  }
  if (!rule.urls || !rule.name)
    return Snackbar['warning']('必须添加规则名或urls！');
  rule.running = true;
  tabs.forEach((tab) => tab.type !== TYPE.PREFER && (tab.disabled = true));
  rule.log = `--------开始优选检测--------`;

  for await (const url of rule.urls.split(/\n/)) {
    const IPs = await fetchIPs(url);
    const host = url.replace(/https?:\/\//, '').trim();
    rule.log = `------共<span class="log-total">${IPs.length}</span>个监测点，请耐心等待⌛️------`;

    rule.content +=
      `#=====${host} 优选结果=====` +
      (await pickBestIP(host, IPs, (loginfo: string) => {
        rule.log += loginfo;

        nextTick(() => {
          logContentEl.value!.lastElementChild?.scrollIntoView({
            behavior: 'smooth',
            block: 'nearest'
          });
        });
      }));
  }
  rule.log += `<div class="log-result">${rule.content}</div>`;
  rule.running = false;
}
</script>

<template>
  <div class="rules-wrapper">
    <!-- TODO : rules props control internal var-dialog-->
    <var-dialog
      title="添加 hosts 规则"
      v-model:show="show"
      @before-close="onBeforeClose"
      @confirm="addRule"
      :confirm-button="activeTab !== TYPE.PREFER"
      :cancel-button="activeTab !== TYPE.PREFER"
    >
      <var-tabs
        elevation
        color="#2979ff"
        active-color="#fff"
        inactive-color="hsla(0, 0%, 100%, .6)"
        v-model:active="activeTab"
        @change="() => (hasError = false)"
      >
        <var-tab
          v-for="({ icon, type, name, disabled }, i) in tabs"
          :key="i"
          :name="type"
          :disabled="disabled"
        >
          <var-icon class="tabs-example-icon" :name="icon" />

          {{ name }}
        </var-tab>
      </var-tabs>

      <var-tabs-items v-model:active="activeTab" :can-swipe="false">
        <!-- 本地自定义 -->
        <var-tab-item :name="TYPE.REGULAR">
          <var-input
            placeholder="方案名称"
            :rules="[(v:string) => !!v || '方案名不能为空']"
            v-model="rule.name"
          />
        </var-tab-item>

        <!-- 自定义源 -->
        <var-tab-item :name="TYPE.REMOTE">
          <var-loading
            description="正在获取"
            type="circle"
            :loading="rule.running"
          >
            <var-input
              placeholder="方案名称"
              :rules="[(v:string) => !!v || '方案名不能为空']"
              v-model="rule.name"
            />
            <var-input
              placeholder="地址:http://,https://"
              :rules="[(v:string) => !!v || '地址不能为空']"
              v-model="rule.urls"
            />
            <var-select placeholder="自动更新" v-model="rule.updateSchedule">
              <var-option label="从不更新" :value="0" />
              <var-option label="每次打开插件" :value="1" />
              <var-option label="每隔四个小时" :value="2" />
            </var-select>
          </var-loading>
        </var-tab-item>

        <!-- 优选 ip 检测 -->
        <var-tab-item :name="TYPE.PREFER" class="rule-prefer">
          <var-row justify="space-between" gutter="20">
            <var-col span="24" style="font-size: 12px">
              通过该工具可以多个地点Ping服务器以检测服务器响应速度
            </var-col>
            <var-col class="rule-urls">
              <var-input placeholder="方案名称" v-model="rule.name" />
            </var-col>
            <var-col span="8">
              <var-input
                placeholder="urls 列表(一行一个)"
                textarea
                v-model="rule.urls"
              />
              <div class="rule-prefer-urls"></div>
            </var-col>
            <var-col span="16" class="rule-prefer-log">
              <div class="rule-prefer-log_title">测试进度</div>
              <div
                class="rule-prefer-log_content"
                v-html="rule.log"
                ref="logContentEl"
              ></div>
            </var-col>
          </var-row>
          <div class="rule-prefer-btn">
            <var-button :loading="rule.running" type="info" @click="startPick">
              {{ rule.log ? '确定优选' : '开始优选' }}
            </var-button>
          </div>
        </var-tab-item>
      </var-tabs-items>
    </var-dialog>
  </div>
</template>

<style lang="scss">
.log-error {
  color: red;
}
.log-success {
  color: #41c64c;
}

.log-total {
  font-style: bold;
  color: #2010b0;
}

.log-result {
  padding: 6px 4px;
  background-color: #35923f;
  color: #fff;
}
</style>
<style lang="scss" scoped>
.rules-wrapper {
  .rule-prefer {
    &-btn {
      margin-top: 14px;
      text-align: center;
    }

    &-log {
      flex-direction: column;
      &_content {
        padding: 2px 6px;
        border: 1px solid #c6cbd1;
        height: 192px;
        overflow-y: scroll;
      }
    }
  }
}
</style>
