<script setup lang="ts">
import '@varlet/ui/es/snackbar/style/index';
import { reactive, watch, nextTick, ref } from 'vue';
import { Snackbar } from '@varlet/ui';
import { useHostsStore } from '@/stores/hosts';
import { useRulesStore } from '@/stores/rules';
import { RULE_TYPE as TYPE } from '@/common/config';
import { getDBData, saveToDB } from '@/common/utils';
// 优选操作
import { fetchIPs, pickBestIP } from '@/common/chinaz/parse';
import type { RuleResult } from '@/stores/rules';

const rulesStore = useRulesStore();
const hostsStore = useHostsStore();

const { setSysHosts, checkNameValid } = hostsStore;
const { updateRule } = rulesStore;

const emit = defineEmits(['update:show']);

const props = defineProps({
  show: Boolean,
  ruleId: {
    type: String,
    required: true
  }
});

// 是否有错误
const hasError = ref(false);
// 优选的日志
const logContentEl = ref<HTMLElement>();
// 激活的 tab
const activeTab = ref(TYPE.LOCAL);

// 填充的数据
let initData: RuleResult = {
  name: '',
  type: activeTab.value,
  order: 0,
  url: '',
  updateSchedule: 0,
  log: '',
  content: '',
  // 正在执行优选！！！
  running: false,
  active: false
};

// 规则数据
const rule = reactive(initData);
// 重置规则
const resetRule = () => {
  activeTab.value = 'local';
  rule.name = '';
  rule.url = '';
  rule.updateSchedule = 0;
  rule.log = '';
  rule.content = '';
  rule.running = false;
  rule.active = false;
};

watch(
  () => [props.show, props.ruleId],
  ([show, id]) => {
    if (id) {
      const { name, type, active, url, order, updateSchedule } = getDBData(
        id as string
      );
      activeTab.value = type;
      rule.name = name;
      rule.type = type;
      rule.active = active;
      rule.order = order;
      rule.url = url;
      rule.updateSchedule = updateSchedule;
    }
    if (!show) {
      resetRule();
      hostsStore.updating = '';
    }
  }
);

// ----关闭对话框前，进行判断----
const onBeforeClose = (
  action: 'confirm' | 'cancel' | 'close',
  done: Function
) => {
  if (rule.running) {
    return;
  }

  if (action === 'close' || action === 'cancel') {
    emit('update:show', false);
  } else {
    if (!hasError.value) {
      done();
      emit('update:show', false);
    } else {
      if (hasError.value) return;
      if (!rule.name) return Snackbar['warning']('必须添加规则名！');
      rule.type === TYPE.REMOTE &&
        !rule.url &&
        Snackbar['warning']('必须添加规则名或url！');
      rule.type === TYPE.PREFER &&
        !rule.content &&
        Snackbar['warning']('未能优选检测！请稍后再试～');
    }
  }
};

// 直接打开添加的规则
const setActive = (id: string) => {
  hostsStore.currentId = id;
  saveToDB(id, rule);
  nextTick(() => setSysHosts());
};

// 验证名称规则
const checkName = (name: string) => {
  const checkValue = checkNameValid(name);
  hasError.value = false;
  if (checkValue !== true) {
    hasError.value = true;
  }
  return checkValue;
};

// 确定添加规则
function updateHostRule() {
  // 如果规则冲突？
  if (hasError.value) return;

  rule.type = activeTab.value;
  // 设置ID
  rule.id = rule.name;

  switch (activeTab.value) {
    case TYPE.LOCAL:
      if (!rule.name) hasError.value = true;
      else {
        hasError.value = false;
        updateRule(rule, props.ruleId);
        setActive(rule.name);
      }
      break;
    case TYPE.REMOTE:
      {
        if (!rule.name || !rule.url) hasError.value = true;
        else {
          hasError.value = false;
          rule.running = true;
          fetch(rule.url).then(
            async (res) => {
              if (res.status !== 200) {
                Snackbar['error']('获取数据出错！');
                rule.running = false;
                return;
              }
              const hosts = await res?.text();
              rule.content = hosts || '';
              rule.running = false;
              updateRule(rule, props.ruleId);
              emit('update:show', false);
              setActive(rule.name);
            },
            (err) => {
              Snackbar['error']('获取数据出错！' + err.toString());
            }
          );
        }
      }
      break;
    case TYPE.PREFER:
      hasError.value = false;
      rule.content += `\n# Generated by utools-plugin-hosts\n# https://github.com/chandlerver5/utools-plugin-hosts\n`;
      updateRule(rule, props.ruleId);
      emit('update:show', false);
      setActive(rule.name);
      break;
    default:
      break;
  }
}

// ----开始测试优选----
async function startPick() {
  // 已有结果，接下来写入优选结果
  if (rule.log && !rule.running) {
    updateHostRule();
    return;
  }
  if (!rule.url || !rule.name)
    return Snackbar['warning']('必须添加规则名或urls！');
  rule.running = true;
  rule.log = `--------开始优选检测--------`;

  for await (const url of rule.url.split(/\n/)) {
    const IPs = await fetchIPs(url);
    const host = url.replace(/https?:\/\//, '').trim();
    rule.log = `------共<span class="log-total">${IPs.length}</span>个监测点，请耐心等待⌛️------`;

    rule.content +=
      `#=====${host} 优选结果=====` +
      (await pickBestIP(host, IPs, (loginfo: string) => {
        rule.log += loginfo;
        nextTick(() => {
          logContentEl.value!.lastElementChild?.scrollIntoView({
            behavior: 'smooth',
            block: 'nearest'
          });
        });
      }));
  }
  rule.log += `<div class="log-result">${rule.content}</div>`;
  rule.running = false;
}
</script>

<template>
  <div class="rules-wrapper">
    <var-dialog
      title="更新 hosts 规则"
      v-model:show="show"
      @before-close="onBeforeClose"
      @confirm="updateHostRule"
      :confirm-button="activeTab !== TYPE.PREFER"
      :cancel-button="activeTab !== TYPE.PREFER"
    >
      <var-tabs
        ref="tabsItemRef"
        elevation
        color="#2979ff"
        active-color="#fff"
        inactive-color="hsla(0, 0%, 100%, .6)"
        @change="
          () => {
            rule.name = '';
            hasError = false;
          }
        "
      >
        <var-tab v-if="activeTab === TYPE.LOCAL">
          <var-icon class="tabs-example-icon" name="file-document-outline" />
          本地
        </var-tab>
        <var-tab v-if="activeTab === TYPE.REMOTE">
          <var-icon class="tabs-example-icon" name="weather-cloudy" />
          远程
        </var-tab>
        <var-tab v-if="activeTab === TYPE.PREFER">
          <var-icon class="tabs-example-icon" name="arrow-down" />
          优选
        </var-tab>
      </var-tabs>

      <var-tabs-items v-model:active="activeTab" :can-swipe="false">
        <!-- 本地自定义 -->
        <var-tab-item :name="TYPE.LOCAL" v-if="activeTab === TYPE.LOCAL">
          <var-input
            placeholder="方案名称"
            :rules="[checkName]"
            v-model="rule.name"
          />
        </var-tab-item>

        <!-- 自定义源 -->
        <var-tab-item :name="TYPE.REMOTE" v-if="activeTab === TYPE.REMOTE">
          <var-loading
            description="正在获取"
            type="circle"
            :loading="rule.running"
          >
            <var-input
              placeholder="方案名称"
              :rules="[checkName]"
              v-model="rule.name"
            />
            <var-input
              placeholder="地址:http://,https://"
              :rules="[(v:string) => (/https?:\/\//).test(v) || '地址错误']"
              v-model="rule.url"
            />
            <var-select placeholder="自动更新" v-model="rule.updateSchedule">
              <var-option label="从不更新" :value="0" />
              <var-option label="每次打开插件" :value="1" />
              <var-option label="每隔四个小时" :value="2" />
            </var-select>
          </var-loading>
        </var-tab-item>

        <!-- 优选 ip 检测 -->
        <var-tab-item
          :name="TYPE.PREFER"
          class="rule-prefer"
          v-if="activeTab === TYPE.REMOTE"
        >
          <var-row justify="space-between" gutter="20">
            <var-col span="24" style="font-size: 12px">
              通过该工具可以多个地点Ping服务器以检测服务器响应速度
            </var-col>
            <var-col class="rule-urls">
              <var-input
                placeholder="方案名称"
                :rules="[checkName]"
                v-model="rule.name"
              />
            </var-col>
            <var-col span="8">
              <var-input
                placeholder="url 列表(一行一个)"
                textarea
                v-model="rule.url"
              />
              <div class="rule-prefer-url"></div>
            </var-col>
            <var-col span="16" class="rule-prefer-log">
              <div class="rule-prefer-log_title">测试进度</div>
              <div
                class="rule-prefer-log_content"
                v-html="rule.log"
                ref="logContentEl"
              ></div>
            </var-col>
          </var-row>
          <div class="rule-prefer-btn">
            <var-button :loading="rule.running" type="info" @click="startPick">
              {{ rule.log ? '确定优选' : '开始优选' }}
            </var-button>
          </div>
        </var-tab-item>
      </var-tabs-items>
    </var-dialog>
  </div>
</template>

<style lang="scss">
.log-error {
  color: red;
}
.log-success {
  color: #41c64c;
}

.log-total {
  font-style: bold;
  color: #2010b0;
}

.log-result {
  padding: 6px 4px;
  background-color: #35923f;
  color: #fff;
}
</style>
<style lang="scss" scoped>
.rules-wrapper {
  .rule-prefer {
    &-btn {
      margin-top: 14px;
      text-align: center;
    }

    &-log {
      flex-direction: column;
      &_content {
        padding: 2px 6px;
        border: 1px solid #c6cbd1;
        height: 192px;
        overflow-y: scroll;
      }
    }
  }
}
</style>
